workflow:
    issue_flow:
        steps:
            open:
                label: "Open"
                order: 10
                allowed_transitions:
                    - start_progress
                    - resolve
                    - close
            in_progress:
                label: "In Progress"
                order: 10
                allowed_transitions:
                    - stop_progress
                    - resolve
                    - close
            closed:
                label: "Closed"
                order: 10
                allowed_transitions:
                    - reopen
            resolved:
                label: "Resolved"
                order: 10
                allowed_transitions:
                    - close
                    - reopen
            reopened:
                label: "Reopened"
                order: 10
                allowed_transitions:
                    - start_progress
