datagrid:
    dashboard-assigned-reported-issues-grid:
        source:
            type: orm
            query:
                select:
                    - issue.id
                    - issue.summary
                    - type.name as taskType
                    - priority.name AS taskPriority
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as taskReporter
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as taskAssignee
                    - issue.created
                    - issue.updated
                from:
                    - { table: OroAcademicalBugTrackingBundle:Issue, alias: issue }
                where:
                    or:
                        - reporter.id = :user
                        - assignee.id = :user
                join:
                    left:
                        - { join: issue.type, alias: type }
                        - { join: issue.priority, alias: priority }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
            bind_parameters:
                user: user
        columns:
            summary:
                label: bugtracking.issue.summary.label
            taskType:
                label: bugtracking.issue.taskType.label
            taskPriority:
                label: bugtracking.issue.taskPriority.label
            taskReporter:
                label: bugtracking.issue.taskReporter.label
            taskAssignee:
                label: bugtracking.issue.taskAssignee.label
            created:
                label: bugtracking.issue.created.label
                frontend_type: datetime
            updated:
                label: bugtracking.issue.updated.label
                frontend_type: datetime
        sorters:
            columns:
                updated:
                    data_name: issue.updated
            default:
                updated: DESC
        options:
            show_step_in_grid: false
            toolbarOptions:
                hide: true
                pageSize:
                    items: [30]
                    default_per_page: 30
    dashboard-recent-issues-grid:
        source:
            type: orm
            query:
                select:
                    - issue.id
                    - issue.summary
                    - type.name as taskType
                    - priority.name AS taskPriority
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as taskReporter
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as taskAssignee
                    - issue.created
                    - issue.updated
                from:
                    - { table: OroAcademicalBugTrackingBundle:Issue, alias: issue }
                where:
                    and:
                        - :logged_user MEMBER OF issue.collaborators
                join:
                    left:
                        - { join: issue.type, alias: type }
                        - { join: issue.priority, alias: priority }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
            bind_parameters:
                logged_user: loggedUser
        columns:
            summary:
                label: bugtracking.issue.summary.label
            taskType:
                label: bugtracking.issue.taskType.label
            taskPriority:
                label: bugtracking.issue.taskPriority.label
            taskReporter:
                label: bugtracking.issue.taskReporter.label
            taskAssignee:
                label: bugtracking.issue.taskAssignee.label
            created:
                label: bugtracking.issue.created.label
                frontend_type: datetime
            updated:
                label: bugtracking.issue.updated.label
                frontend_type: datetime
        sorters:
            columns:
                summary:
                    data_name : issue.summary
                taskType:
                    data_name: taskType
                taskPriority:
                    data_name: priority.priority
                taskReporter:
                    data_name: taskReporter
                taskAssignee:
                    data_name: taskAssignee
                created:
                    data_name: issue.created
                updated:
                    data_name: issue.updated
            default:
                updated: DESC
        options:
            show_step_in_grid: false
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10
    bugtracking-issues-grid:
        source:
            type: orm
            query:
                select:
                    - issue.id
                    - issue.summary
                    - issue.code
                    - issue.description
                    - type.name as taskType
                    - priority.name AS taskPriority
                    - resolution.name AS taskResolution
                    - issue.status
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as taskReporter
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as taskAssignee
                    - issue.created
                    - issue.updated
                    - collaborators.username
                from:
                    - { table: OroAcademicalBugTrackingBundle:Issue, alias: issue }
                join:
                    left:
                        - { join: issue.type, alias: type }
                        - { join: issue.priority, alias: priority }
                        - { join: issue.resolution, alias: resolution}
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
                        - { join: issue.collaborators, alias: collaborators}
        columns:
            summary:
                label: bugtracking.issue.summary.label
            code:
                label: bugtracking.issue.code.label
            description:
                label: bugtracking.issue.description.label
            taskType:
                label: bugtracking.issue.taskType.label
            taskPriority:
                label: bugtracking.issue.taskPriority.label
            taskResolution:
                label: bugtracking.issue.taskResolution.label
            status:
                label: bugtracking.issue.status.label
            taskReporter:
                label: bugtracking.issue.taskReporter.label
            taskAssignee:
                label: bugtracking.issue.taskAssignee.label
            created:
                label: bugtracking.issue.created.label
                frontend_type: datetime
            updated:
                label: bugtracking.issue.updated.label
                frontend_type: datetime
            collaborators:
                label: bugtracking.issue.collaborators.label
        sorters:
            columns:
                summary:
                    data_name : issue.summary
                code:
                    data_name: issue.code
                description:
                    data_name: issue.description
                taskType:
                    data_name: taskType
                taskPriority:
                    data_name: priority.priority
                taskResolution:
                    data_name: taskResolution
                status:
                    data_name: issue.status
                taskReporter:
                    data_name: taskReporter
                taskAssignee:
                    data_name: taskAssignee
                created:
                    data_name: issue.created
                updated:
                    data_name: issue.updated
            default:
                updated: DESC
        filters:
            columns:
                summary:
                    type: string
                    data_name : issue.summary
                code:
                    type: string
                    data_name: issue.code
                description:
                    type: string
                    data_name: issue.description
                taskType:
                    type: string
                    data_name: taskType
                taskPriority:
                    type: string
                    data_name: taskPriority
                taskResolution:
                    type: string
                    data_name: taskResolution
                status:
                    type: string
                    data_name: issue.status
                taskReporter:
                    type: string
                    data_name: taskReporter
                taskAssignee:
                    type: string
                    data_name: taskAssignee
                created:
                    type: datetime
                    data_name: issue.created
                updated:
                    type: datetime
                    data_name: issue.updated
                collaborator:
                    type: choice-tree
                    data_name: collaborators
                    options:
                        data: @oro_user.provider.filter.user_choice_tree->getList
        properties:
            id: ~
            view_link:
                type:       url
                route:      bugtracking_issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      bugtracking_issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      bugtracking_issue_api_delete_issue
                params:     [ id ]
        actions:
            view:
                type:       navigate
                label:      bugtracking.datagrid.view
                icon:       eye-open
                link:       view_link
                rowAction:  true
            update:
                type:       navigate
                label:      bugtracking.datagrid.update
                icon:       edit
                link:       update_link
            delete:
                type:       delete
                label:      bugtracking.datagrid.delete
                icon:       trash
                link:       delete_link
        mass_actions:
            delete:
                type: delete
                entity_name: %oroacademical_bugtracking.issue.entity.class%
                data_identifier: issue.id
                label: bugtracking.datagrid.delete
                icon: trash
