oro_menu_config:
    items:
        issue_list:
            label: Issues
            route: bugtracking_issue_index
    tree:
        application_menu:
            children:
                issue_list: ~
