items:
    bugtracking_add_issue_button:
        template: OroAcademicalBugTrackingBundle:Dashboard:addButton.html.twig
        applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)'

placeholders:
    view_navButtons_before:
        items:
            bugtracking_add_issue_button:
                order: 100
