items:
    bugtracking_add_issue_button:
        template: OroAcademicalBugTrackingBundle:Dashboard:addButton.html.twig
        applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)'
    bugtracking_assigned_reported_issues_grid:
        template: OroAcademicalBugTrackingBundle:Issue:assignedReportedIssues.html.twig
        applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)'

placeholders:
    view_navButtons_before:
        items:
            bugtracking_add_issue_button:
                order: 100
    view_content_data_additional_information:
        items:
            bugtracking_assigned_reported_issues_grid:
                order: 100
